import { test, expect } from '@playwright/test';

for (const colorScheme of ['light', 'dark'] as const) test(`resize retains navigation and preview in ${colorScheme} mode`, async ({page}, info) => {
  await page.emulateMedia({colorScheme});
  await page.goto('/');
  await page.getByRole('button', {name:'Explore an example'}).click();
  await page.locator('.preview').evaluate(el => { el.textContent='0.1.0-development.with.a.long.label+g123456789012.dirty'; });
  const pane=page.locator('#content');
  const browse=page.getByRole('button', {name:'Operations & filters',exact:true});
  const sidebar=page.locator('.sidebar');
  await page.getByRole('searchbox',{name:'Search operations'}).focus();
  await page.setViewportSize({width:600,height:500});
  await expect(browse).toBeFocused();
  await expect(sidebar).toBeHidden();
  await expect(pane.locator('h1')).toBeInViewport();
  expect((await pane.boundingBox())!.width).toBeGreaterThan(550);
  await page.keyboard.press('Enter');
  await expect(browse).toHaveAttribute('aria-expanded','true');
  await expect(pane).toBeHidden();
  await page.getByRole('searchbox',{name:'Search operations'}).focus();
  await page.keyboard.press('Escape');
  await expect(browse).toBeFocused();
  await expect(pane).toBeVisible();
  await page.keyboard.press('Enter');
  await page.getByRole('searchbox',{name:'Search operations'}).fill('/pets');
  const operation=page.locator('.operation-button').last();
  const selected=await operation.getAttribute('aria-label');
  await operation.focus(); await page.keyboard.press('Enter');
  await expect(pane).toBeFocused();
  await expect(browse).toHaveAttribute('aria-expanded','false');
  await expect(pane.locator('h1')).toBeInViewport();
  await page.setViewportSize({width:1360,height:900});
  await expect(page.locator('.operation-button[aria-current]')).toHaveAttribute('aria-label',selected!);
  await expect(page.getByRole('searchbox',{name:'Search operations'})).toHaveValue('/pets');
  await page.getByRole('button',{name:'Schemas',exact:true}).click();
  await page.getByRole('button',{name:'Pet →',exact:true}).click();
  await page.setViewportSize({width:480,height:500});
  await expect(pane.getByRole('heading',{name:'Pet',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Rules and preview',exact:true}).click();
  await page.getByRole('checkbox',{name:'Bundle external references into one file'}).check();
  await page.getByRole('button',{name:'Preview these rules'}).click();
  await expect(page.getByRole('button',{name:'Export reviewed output'})).toBeVisible();
  const config=await page.getByLabel('Rules JSON (copy to save, paste to replay)').inputValue();
  const preview=await page.locator('.preview-result').textContent();
  for(const [width,height] of [[390,844],[480,500],[600,500],[800,600],[801,600],[900,600],[1024,768],[1440,900]]) {
    await page.setViewportSize({width,height});
    await expect(page.locator('.preview-result')).toHaveText(preview!);
    await expect(page.getByLabel('Rules JSON (copy to save, paste to replay)')).toHaveValue(config);
    expect(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
    expect(await page.evaluate(()=>window.scrollY)).toBe(0);
    const header=await page.locator('.app-header').boundingBox();
    const theme=await page.locator('#theme').boundingBox();
    const version=await page.locator('.preview').boundingBox();
    expect(version!.height).toBeLessThan(25);
    expect(theme!.x+theme!.width).toBeLessThanOrEqual(width);
    expect(version!.x+version!.width).toBeLessThanOrEqual(theme!.x);
    expect(theme!.y+theme!.height).toBeLessThanOrEqual(header!.height);
    expect((await pane.boundingBox())!.height).toBeGreaterThan(190);
    await page.getByRole('button',{name:'Export reviewed output'}).scrollIntoViewIfNeeded();
    await expect(page.getByRole('button',{name:'Export reviewed output'})).toBeInViewport();
  }
  await page.setViewportSize({width:600,height:500});
  const detailScroll=await pane.evaluate(el=>el.scrollTop);
  await browse.click(); await browse.click();
  expect(await pane.evaluate(el=>el.scrollTop)).toBe(detailScroll);
  await expect(page.locator('.preview-result')).toHaveText(preview!);
  await page.screenshot({path:`artifacts/${info.project.name}-resize-${colorScheme}.png`});
});
