import { build } from 'esbuild';
import { mkdir, copyFile, readFile, writeFile } from 'node:fs/promises';
import { buildVersion } from './version.mjs';
import { playgroundVersion } from './playground-version.mjs';
const version = buildVersion();
const playground = playgroundVersion({ build: version });
await build({ entryPoints: ['packages/desktop/import.ts'], outfile: 'dist/desktop/import.cjs', bundle: true, platform: 'node', mainFields: ['module', 'main'], format: 'cjs', target: ['node22'], legalComments: 'eof' });
await mkdir('dist/web', { recursive: true });
const sample = await Promise.all(['petstore.yaml', 'schemas/pet.yaml'].map(async id => ({ id, text: await readFile(`tests/fixtures/${id}`, 'utf8') })));
await build({ define: { __SPECREFIT_BUILD__: JSON.stringify(version), __SPECREFIT_PLAYGROUND__: JSON.stringify(playground) }, entryPoints: { app: 'apps/web/app.ts', worker: 'apps/web/worker.ts' }, outdir: 'dist/web', bundle: true, platform: 'browser', format: 'esm', target: ['es2022'], legalComments: 'eof', plugins: [{ name: 'sample', setup(b) { b.onResolve({ filter: /sample\.json$/ }, () => ({ path: 'sample', namespace: 'sample' })); b.onLoad({ filter: /.*/, namespace: 'sample' }, () => ({ contents: JSON.stringify(sample), loader: 'json' })); } }] });
for (const file of ['index.html', 'styles.css', 'mark.svg']) await copyFile(`apps/web/${file}`, `dist/web/${file}`);
await copyFile('LICENSE', 'dist/web/LICENSE');
await writeFile('dist/web/version.json', JSON.stringify(version, null, 2) + '\n');
await writeFile('dist/web/playground-version.json', JSON.stringify(playground, null, 2) + '\n');
await writeFile('dist/web/THIRD_PARTY_NOTICES.txt', `SpecRefit includes yaml 2.9.1 (ISC).\n\n${await readFile('node_modules/yaml/LICENSE', 'utf8')}\n\nSpecRefit includes jsonc-parser 3.3.1 (MIT).\n\n${await readFile('node_modules/jsonc-parser/LICENSE.md', 'utf8')}`);
await writeFile('dist/web/THIRD_PARTY_NOTICES.txt', `\n\nSpecRefit includes fflate 0.8.3 (MIT).\n\n${await readFile('node_modules/fflate/LICENSE', 'utf8')}`, { flag: 'a' });
console.log(`Built SpecRefit ${version.version}: shared editor and worker in dist/web.`);
